// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOzPRW8aKp6YEug95lFXETwvTnUfy_XIc',
    appId: '1:1061498567120:web:39228f4ea53dc29637a1d5',
    messagingSenderId: '1061498567120',
    projectId: 'store-9b01c',
    authDomain: 'store-9b01c.firebaseapp.com',
    storageBucket: 'store-9b01c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2FrGFCxRDdKGxCE_y0HACVxRUXD0oqzo',
    appId: '1:1061498567120:android:f00523ad3a32cda037a1d5',
    messagingSenderId: '1061498567120',
    projectId: 'store-9b01c',
    storageBucket: 'store-9b01c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPqSDT6toZb8gkawzckEwdtMgSXue9_wo',
    appId: '1:1061498567120:ios:cf5312ed8b982dbd37a1d5',
    messagingSenderId: '1061498567120',
    projectId: 'store-9b01c',
    storageBucket: 'store-9b01c.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPqSDT6toZb8gkawzckEwdtMgSXue9_wo',
    appId: '1:1061498567120:ios:cf5312ed8b982dbd37a1d5',
    messagingSenderId: '1061498567120',
    projectId: 'store-9b01c',
    storageBucket: 'store-9b01c.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOzPRW8aKp6YEug95lFXETwvTnUfy_XIc',
    appId: '1:1061498567120:web:968e244d87c7bff337a1d5',
    messagingSenderId: '1061498567120',
    projectId: 'store-9b01c',
    authDomain: 'store-9b01c.firebaseapp.com',
    storageBucket: 'store-9b01c.appspot.com',
  );
}
